//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MembershipCashierDL.Tests.MPSvc {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Node", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.MemberBindingNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.MemberNodeGeneric))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.TypeNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.MethodInfoNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.PropertyInfoNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.ConstructorInfoNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.FieldInfoNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.MemberInfoNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.MemberMemberBindingNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.MemberListBindingNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.ElementInitNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.MemberAssignmentNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.ExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.ExpressionNodeGeneric))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.MemberInitExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.NewExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.ConditionalExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.MethodCallExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.NewArrayExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.MemberExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.ParameterExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.TypeBinaryExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.UnaryExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.BinaryExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.ConstantExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.InvocationExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.LambdaExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.ListInitExpressionNode))]
    public partial class Node : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MemberBindingNode", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.MemberMemberBindingNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.MemberListBindingNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.MemberAssignmentNode))]
    public partial class MemberBindingNode : MembershipCashierDL.Tests.MPSvc.Node {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Linq.Expressions.MemberBindingType BindingTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.MPSvc.MemberInfoNode MemberField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Linq.Expressions.MemberBindingType BindingType {
            get {
                return this.BindingTypeField;
            }
            set {
                if ((this.BindingTypeField.Equals(value) != true)) {
                    this.BindingTypeField = value;
                    this.RaisePropertyChanged("BindingType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.MPSvc.MemberInfoNode Member {
            get {
                return this.MemberField;
            }
            set {
                if ((object.ReferenceEquals(this.MemberField, value) != true)) {
                    this.MemberField = value;
                    this.RaisePropertyChanged("Member");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MemberNodeGeneric", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.MethodInfoNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.PropertyInfoNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.ConstructorInfoNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.FieldInfoNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.MemberInfoNode))]
    public partial class MemberNodeGeneric : MembershipCashierDL.Tests.MPSvc.Node {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.MPSvc.TypeNode DeclaringTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SignatureField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.MPSvc.TypeNode DeclaringType {
            get {
                return this.DeclaringTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.DeclaringTypeField, value) != true)) {
                    this.DeclaringTypeField = value;
                    this.RaisePropertyChanged("DeclaringType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Signature {
            get {
                return this.SignatureField;
            }
            set {
                if ((object.ReferenceEquals(this.SignatureField, value) != true)) {
                    this.SignatureField = value;
                    this.RaisePropertyChanged("Signature");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TypeNode", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes")]
    [System.SerializableAttribute()]
    public partial class TypeNode : MembershipCashierDL.Tests.MPSvc.Node {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.MPSvc.TypeNode[] GenericArgumentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.MPSvc.TypeNode[] GenericArguments {
            get {
                return this.GenericArgumentsField;
            }
            set {
                if ((object.ReferenceEquals(this.GenericArgumentsField, value) != true)) {
                    this.GenericArgumentsField = value;
                    this.RaisePropertyChanged("GenericArguments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MethodInfoNode", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes")]
    [System.SerializableAttribute()]
    public partial class MethodInfoNode : MembershipCashierDL.Tests.MPSvc.MemberNodeGeneric {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.MPSvc.TypeNode[] GenericArgumentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsGenericMethodField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.MPSvc.TypeNode[] GenericArguments {
            get {
                return this.GenericArgumentsField;
            }
            set {
                if ((object.ReferenceEquals(this.GenericArgumentsField, value) != true)) {
                    this.GenericArgumentsField = value;
                    this.RaisePropertyChanged("GenericArguments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public bool IsGenericMethod {
            get {
                return this.IsGenericMethodField;
            }
            set {
                if ((this.IsGenericMethodField.Equals(value) != true)) {
                    this.IsGenericMethodField = value;
                    this.RaisePropertyChanged("IsGenericMethod");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PropertyInfoNode", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes")]
    [System.SerializableAttribute()]
    public partial class PropertyInfoNode : MembershipCashierDL.Tests.MPSvc.MemberNodeGeneric {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConstructorInfoNode", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes")]
    [System.SerializableAttribute()]
    public partial class ConstructorInfoNode : MembershipCashierDL.Tests.MPSvc.MemberNodeGeneric {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FieldInfoNode", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes")]
    [System.SerializableAttribute()]
    public partial class FieldInfoNode : MembershipCashierDL.Tests.MPSvc.MemberNodeGeneric {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MemberInfoNode", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes")]
    [System.SerializableAttribute()]
    public partial class MemberInfoNode : MembershipCashierDL.Tests.MPSvc.MemberNodeGeneric {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MemberMemberBindingNode", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes")]
    [System.SerializableAttribute()]
    public partial class MemberMemberBindingNode : MembershipCashierDL.Tests.MPSvc.MemberBindingNode {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.MPSvc.MemberBindingNodeList BindingsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.MPSvc.MemberBindingNodeList Bindings {
            get {
                return this.BindingsField;
            }
            set {
                if ((object.ReferenceEquals(this.BindingsField, value) != true)) {
                    this.BindingsField = value;
                    this.RaisePropertyChanged("Bindings");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MemberListBindingNode", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes")]
    [System.SerializableAttribute()]
    public partial class MemberListBindingNode : MembershipCashierDL.Tests.MPSvc.MemberBindingNode {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.MPSvc.ElementInitNodeList InitializersField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.MPSvc.ElementInitNodeList Initializers {
            get {
                return this.InitializersField;
            }
            set {
                if ((object.ReferenceEquals(this.InitializersField, value) != true)) {
                    this.InitializersField = value;
                    this.RaisePropertyChanged("Initializers");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ElementInitNode", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes")]
    [System.SerializableAttribute()]
    public partial class ElementInitNode : MembershipCashierDL.Tests.MPSvc.Node {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.MPSvc.MethodInfoNode AddMethodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.MPSvc.ExpressionNodeList ArgumentsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.MPSvc.MethodInfoNode AddMethod {
            get {
                return this.AddMethodField;
            }
            set {
                if ((object.ReferenceEquals(this.AddMethodField, value) != true)) {
                    this.AddMethodField = value;
                    this.RaisePropertyChanged("AddMethod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.MPSvc.ExpressionNodeList Arguments {
            get {
                return this.ArgumentsField;
            }
            set {
                if ((object.ReferenceEquals(this.ArgumentsField, value) != true)) {
                    this.ArgumentsField = value;
                    this.RaisePropertyChanged("Arguments");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MemberAssignmentNode", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes")]
    [System.SerializableAttribute()]
    public partial class MemberAssignmentNode : MembershipCashierDL.Tests.MPSvc.MemberBindingNode {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.MPSvc.ExpressionNode ExpressionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.MPSvc.ExpressionNode Expression {
            get {
                return this.ExpressionField;
            }
            set {
                if ((object.ReferenceEquals(this.ExpressionField, value) != true)) {
                    this.ExpressionField = value;
                    this.RaisePropertyChanged("Expression");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExpressionNode", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.ExpressionNodeGeneric))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.MemberInitExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.NewExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.ConditionalExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.MethodCallExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.NewArrayExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.MemberExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.ParameterExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.TypeBinaryExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.UnaryExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.BinaryExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.ConstantExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.InvocationExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.LambdaExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.ListInitExpressionNode))]
    public partial class ExpressionNode : MembershipCashierDL.Tests.MPSvc.Node {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Linq.Expressions.ExpressionType NodeTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.MPSvc.TypeNode TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Linq.Expressions.ExpressionType NodeType {
            get {
                return this.NodeTypeField;
            }
            set {
                if ((this.NodeTypeField.Equals(value) != true)) {
                    this.NodeTypeField = value;
                    this.RaisePropertyChanged("NodeType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.MPSvc.TypeNode Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExpressionNodeGeneric", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.MemberInitExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.NewExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.ConditionalExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.MethodCallExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.NewArrayExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.MemberExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.ParameterExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.TypeBinaryExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.UnaryExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.BinaryExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.ConstantExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.InvocationExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.LambdaExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.ListInitExpressionNode))]
    public partial class ExpressionNodeGeneric : MembershipCashierDL.Tests.MPSvc.ExpressionNode {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MemberInitExpressionNode", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes")]
    [System.SerializableAttribute()]
    public partial class MemberInitExpressionNode : MembershipCashierDL.Tests.MPSvc.ExpressionNodeGeneric {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.MPSvc.MemberBindingNodeList BindingsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.MPSvc.NewExpressionNode NewExpressionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.MPSvc.MemberBindingNodeList Bindings {
            get {
                return this.BindingsField;
            }
            set {
                if ((object.ReferenceEquals(this.BindingsField, value) != true)) {
                    this.BindingsField = value;
                    this.RaisePropertyChanged("Bindings");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.MPSvc.NewExpressionNode NewExpression {
            get {
                return this.NewExpressionField;
            }
            set {
                if ((object.ReferenceEquals(this.NewExpressionField, value) != true)) {
                    this.NewExpressionField = value;
                    this.RaisePropertyChanged("NewExpression");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NewExpressionNode", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes")]
    [System.SerializableAttribute()]
    public partial class NewExpressionNode : MembershipCashierDL.Tests.MPSvc.ExpressionNodeGeneric {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.MPSvc.ExpressionNodeList ArgumentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.MPSvc.ConstructorInfoNode ConstructorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.MPSvc.MemberInfoNodeList MembersField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.MPSvc.ExpressionNodeList Arguments {
            get {
                return this.ArgumentsField;
            }
            set {
                if ((object.ReferenceEquals(this.ArgumentsField, value) != true)) {
                    this.ArgumentsField = value;
                    this.RaisePropertyChanged("Arguments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.MPSvc.ConstructorInfoNode Constructor {
            get {
                return this.ConstructorField;
            }
            set {
                if ((object.ReferenceEquals(this.ConstructorField, value) != true)) {
                    this.ConstructorField = value;
                    this.RaisePropertyChanged("Constructor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.MPSvc.MemberInfoNodeList Members {
            get {
                return this.MembersField;
            }
            set {
                if ((object.ReferenceEquals(this.MembersField, value) != true)) {
                    this.MembersField = value;
                    this.RaisePropertyChanged("Members");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConditionalExpressionNode", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes")]
    [System.SerializableAttribute()]
    public partial class ConditionalExpressionNode : MembershipCashierDL.Tests.MPSvc.ExpressionNodeGeneric {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.MPSvc.ExpressionNode IfFalseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.MPSvc.ExpressionNode IfTrueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.MPSvc.ExpressionNode TestField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.MPSvc.ExpressionNode IfFalse {
            get {
                return this.IfFalseField;
            }
            set {
                if ((object.ReferenceEquals(this.IfFalseField, value) != true)) {
                    this.IfFalseField = value;
                    this.RaisePropertyChanged("IfFalse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.MPSvc.ExpressionNode IfTrue {
            get {
                return this.IfTrueField;
            }
            set {
                if ((object.ReferenceEquals(this.IfTrueField, value) != true)) {
                    this.IfTrueField = value;
                    this.RaisePropertyChanged("IfTrue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.MPSvc.ExpressionNode Test {
            get {
                return this.TestField;
            }
            set {
                if ((object.ReferenceEquals(this.TestField, value) != true)) {
                    this.TestField = value;
                    this.RaisePropertyChanged("Test");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MethodCallExpressionNode", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes")]
    [System.SerializableAttribute()]
    public partial class MethodCallExpressionNode : MembershipCashierDL.Tests.MPSvc.ExpressionNodeGeneric {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.MPSvc.ExpressionNodeList ArgumentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.MPSvc.MethodInfoNode MethodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.MPSvc.ExpressionNode ObjectField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.MPSvc.ExpressionNodeList Arguments {
            get {
                return this.ArgumentsField;
            }
            set {
                if ((object.ReferenceEquals(this.ArgumentsField, value) != true)) {
                    this.ArgumentsField = value;
                    this.RaisePropertyChanged("Arguments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.MPSvc.MethodInfoNode Method {
            get {
                return this.MethodField;
            }
            set {
                if ((object.ReferenceEquals(this.MethodField, value) != true)) {
                    this.MethodField = value;
                    this.RaisePropertyChanged("Method");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.MPSvc.ExpressionNode Object {
            get {
                return this.ObjectField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjectField, value) != true)) {
                    this.ObjectField = value;
                    this.RaisePropertyChanged("Object");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NewArrayExpressionNode", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes")]
    [System.SerializableAttribute()]
    public partial class NewArrayExpressionNode : MembershipCashierDL.Tests.MPSvc.ExpressionNodeGeneric {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.MPSvc.ExpressionNodeList ExpressionsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.MPSvc.ExpressionNodeList Expressions {
            get {
                return this.ExpressionsField;
            }
            set {
                if ((object.ReferenceEquals(this.ExpressionsField, value) != true)) {
                    this.ExpressionsField = value;
                    this.RaisePropertyChanged("Expressions");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MemberExpressionNode", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes")]
    [System.SerializableAttribute()]
    public partial class MemberExpressionNode : MembershipCashierDL.Tests.MPSvc.ExpressionNodeGeneric {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.MPSvc.ExpressionNode ExpressionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.MPSvc.MemberInfoNode MemberField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.MPSvc.ExpressionNode Expression {
            get {
                return this.ExpressionField;
            }
            set {
                if ((object.ReferenceEquals(this.ExpressionField, value) != true)) {
                    this.ExpressionField = value;
                    this.RaisePropertyChanged("Expression");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.MPSvc.MemberInfoNode Member {
            get {
                return this.MemberField;
            }
            set {
                if ((object.ReferenceEquals(this.MemberField, value) != true)) {
                    this.MemberField = value;
                    this.RaisePropertyChanged("Member");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParameterExpressionNode", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes")]
    [System.SerializableAttribute()]
    public partial class ParameterExpressionNode : MembershipCashierDL.Tests.MPSvc.ExpressionNodeGeneric {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsByRefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public bool IsByRef {
            get {
                return this.IsByRefField;
            }
            set {
                if ((this.IsByRefField.Equals(value) != true)) {
                    this.IsByRefField = value;
                    this.RaisePropertyChanged("IsByRef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TypeBinaryExpressionNode", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes")]
    [System.SerializableAttribute()]
    public partial class TypeBinaryExpressionNode : MembershipCashierDL.Tests.MPSvc.ExpressionNodeGeneric {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.MPSvc.ExpressionNode ExpressionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.MPSvc.TypeNode TypeOperandField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.MPSvc.ExpressionNode Expression {
            get {
                return this.ExpressionField;
            }
            set {
                if ((object.ReferenceEquals(this.ExpressionField, value) != true)) {
                    this.ExpressionField = value;
                    this.RaisePropertyChanged("Expression");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.MPSvc.TypeNode TypeOperand {
            get {
                return this.TypeOperandField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeOperandField, value) != true)) {
                    this.TypeOperandField = value;
                    this.RaisePropertyChanged("TypeOperand");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnaryExpressionNode", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes")]
    [System.SerializableAttribute()]
    public partial class UnaryExpressionNode : MembershipCashierDL.Tests.MPSvc.ExpressionNodeGeneric {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.MPSvc.ExpressionNode OperandField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.MPSvc.ExpressionNode Operand {
            get {
                return this.OperandField;
            }
            set {
                if ((object.ReferenceEquals(this.OperandField, value) != true)) {
                    this.OperandField = value;
                    this.RaisePropertyChanged("Operand");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BinaryExpressionNode", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes")]
    [System.SerializableAttribute()]
    public partial class BinaryExpressionNode : MembershipCashierDL.Tests.MPSvc.ExpressionNodeGeneric {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.MPSvc.ExpressionNode ConversionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsLiftedToNullField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.MPSvc.ExpressionNode LeftField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.MPSvc.MethodInfoNode MethodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.MPSvc.ExpressionNode RightField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.MPSvc.ExpressionNode Conversion {
            get {
                return this.ConversionField;
            }
            set {
                if ((object.ReferenceEquals(this.ConversionField, value) != true)) {
                    this.ConversionField = value;
                    this.RaisePropertyChanged("Conversion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public bool IsLiftedToNull {
            get {
                return this.IsLiftedToNullField;
            }
            set {
                if ((this.IsLiftedToNullField.Equals(value) != true)) {
                    this.IsLiftedToNullField = value;
                    this.RaisePropertyChanged("IsLiftedToNull");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.MPSvc.ExpressionNode Left {
            get {
                return this.LeftField;
            }
            set {
                if ((object.ReferenceEquals(this.LeftField, value) != true)) {
                    this.LeftField = value;
                    this.RaisePropertyChanged("Left");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.MPSvc.MethodInfoNode Method {
            get {
                return this.MethodField;
            }
            set {
                if ((object.ReferenceEquals(this.MethodField, value) != true)) {
                    this.MethodField = value;
                    this.RaisePropertyChanged("Method");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.MPSvc.ExpressionNode Right {
            get {
                return this.RightField;
            }
            set {
                if ((object.ReferenceEquals(this.RightField, value) != true)) {
                    this.RightField = value;
                    this.RaisePropertyChanged("Right");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConstantExpressionNode", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Linq.Expressions.MemberBindingType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Linq.Expressions.ExpressionType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierUnified.Contracts.CreditTransactionDiscriminator))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierUnified.Contracts.CreditTransactionContract[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierUnified.Contracts.CreditTransactionContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierUnified.Contracts.CreditTransactionImplementor))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierUnified.Contracts.LocationDiscriminator))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierUnified.Contracts.LocationContract[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierUnified.Contracts.LocationContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierUnified.Contracts.LocationImplementor))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierUnified.Contracts.OwnerDiscriminator))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierUnified.Contracts.OwnerContract[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierUnified.Contracts.OwnerContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierUnified.Contracts.ProfileCreditDiscriminator))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierUnified.Contracts.ProfileCreditContract[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierUnified.Contracts.ProfileCreditContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.ExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.Node))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.MemberMemberBindingNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.MemberBindingNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.MemberInfoNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.MemberNodeGeneric))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.TypeNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.TypeNode[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.MemberInfoNodeList))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.MemberInitExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.ExpressionNodeGeneric))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.MemberListBindingNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.ElementInitNodeList))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.ElementInitNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.MethodInfoNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.ConditionalExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.MethodCallExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.ExpressionNodeList))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.NewArrayExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.MemberExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.ParameterExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.PropertyInfoNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.TypeBinaryExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.UnaryExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.MemberBindingNodeList))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.BinaryExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.MemberAssignmentNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.NewExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.ConstructorInfoNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.FieldInfoNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.InvocationExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.LambdaExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.ListInitExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.MPSvc.ExpressionNode[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SecurityUnified.Contracts.DataDiscriminator<object>))]
    public partial class ConstantExpressionNode : MembershipCashierDL.Tests.MPSvc.ExpressionNodeGeneric {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public object Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvocationExpressionNode", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes")]
    [System.SerializableAttribute()]
    public partial class InvocationExpressionNode : MembershipCashierDL.Tests.MPSvc.ExpressionNodeGeneric {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.MPSvc.ExpressionNodeList ArgumentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.MPSvc.ExpressionNode ExpressionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.MPSvc.ExpressionNodeList Arguments {
            get {
                return this.ArgumentsField;
            }
            set {
                if ((object.ReferenceEquals(this.ArgumentsField, value) != true)) {
                    this.ArgumentsField = value;
                    this.RaisePropertyChanged("Arguments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.MPSvc.ExpressionNode Expression {
            get {
                return this.ExpressionField;
            }
            set {
                if ((object.ReferenceEquals(this.ExpressionField, value) != true)) {
                    this.ExpressionField = value;
                    this.RaisePropertyChanged("Expression");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LambdaExpressionNode", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes")]
    [System.SerializableAttribute()]
    public partial class LambdaExpressionNode : MembershipCashierDL.Tests.MPSvc.ExpressionNodeGeneric {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.MPSvc.ExpressionNode BodyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.MPSvc.ExpressionNodeList ParametersField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.MPSvc.ExpressionNode Body {
            get {
                return this.BodyField;
            }
            set {
                if ((object.ReferenceEquals(this.BodyField, value) != true)) {
                    this.BodyField = value;
                    this.RaisePropertyChanged("Body");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.MPSvc.ExpressionNodeList Parameters {
            get {
                return this.ParametersField;
            }
            set {
                if ((object.ReferenceEquals(this.ParametersField, value) != true)) {
                    this.ParametersField = value;
                    this.RaisePropertyChanged("Parameters");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListInitExpressionNode", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes")]
    [System.SerializableAttribute()]
    public partial class ListInitExpressionNode : MembershipCashierDL.Tests.MPSvc.ExpressionNodeGeneric {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.MPSvc.ElementInitNodeList InitializersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.MPSvc.ExpressionNode NewExpressionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.MPSvc.ElementInitNodeList Initializers {
            get {
                return this.InitializersField;
            }
            set {
                if ((object.ReferenceEquals(this.InitializersField, value) != true)) {
                    this.InitializersField = value;
                    this.RaisePropertyChanged("Initializers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.MPSvc.ExpressionNode NewExpression {
            get {
                return this.NewExpressionField;
            }
            set {
                if ((object.ReferenceEquals(this.NewExpressionField, value) != true)) {
                    this.NewExpressionField = value;
                    this.RaisePropertyChanged("NewExpression");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="MemberBindingNodeList", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes", ItemName="MemberBindingNode")]
    [System.SerializableAttribute()]
    public class MemberBindingNodeList : System.Collections.Generic.List<MembershipCashierDL.Tests.MPSvc.MemberBindingNode> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ElementInitNodeList", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes", ItemName="ElementInitNode")]
    [System.SerializableAttribute()]
    public class ElementInitNodeList : System.Collections.Generic.List<MembershipCashierDL.Tests.MPSvc.ElementInitNode> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ExpressionNodeList", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes", ItemName="ExpressionNode")]
    [System.SerializableAttribute()]
    public class ExpressionNodeList : System.Collections.Generic.List<MembershipCashierDL.Tests.MPSvc.ExpressionNode> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="MemberInfoNodeList", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes", ItemName="MemberInfoNode")]
    [System.SerializableAttribute()]
    public class MemberInfoNodeList : System.Collections.Generic.List<MembershipCashierDL.Tests.MPSvc.MemberInfoNode> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MPSvc.LowLevelForMembershipCashierDL")]
    public interface LowLevelForMembershipCashierDL {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILowLevelAccess/FindCreditTransaction", ReplyAction="http://tempuri.org/ILowLevelAccess/FindCreditTransactionResponse")]
        MembershipCashierUnified.Contracts.CreditTransactionContract[] FindCreditTransaction(MembershipCashierUnified.Contracts.CreditTransactionDiscriminator d);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILowLevelAccess/FindCreditTransaction", ReplyAction="http://tempuri.org/ILowLevelAccess/FindCreditTransactionResponse")]
        System.Threading.Tasks.Task<MembershipCashierUnified.Contracts.CreditTransactionContract[]> FindCreditTransactionAsync(MembershipCashierUnified.Contracts.CreditTransactionDiscriminator d);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILowLevelAccess/FindLocation", ReplyAction="http://tempuri.org/ILowLevelAccess/FindLocationResponse")]
        MembershipCashierUnified.Contracts.LocationContract[] FindLocation(MembershipCashierUnified.Contracts.LocationDiscriminator d);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILowLevelAccess/FindLocation", ReplyAction="http://tempuri.org/ILowLevelAccess/FindLocationResponse")]
        System.Threading.Tasks.Task<MembershipCashierUnified.Contracts.LocationContract[]> FindLocationAsync(MembershipCashierUnified.Contracts.LocationDiscriminator d);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILowLevelAccess/FindOwner", ReplyAction="http://tempuri.org/ILowLevelAccess/FindOwnerResponse")]
        MembershipCashierUnified.Contracts.OwnerContract[] FindOwner(MembershipCashierUnified.Contracts.OwnerDiscriminator d);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILowLevelAccess/FindOwner", ReplyAction="http://tempuri.org/ILowLevelAccess/FindOwnerResponse")]
        System.Threading.Tasks.Task<MembershipCashierUnified.Contracts.OwnerContract[]> FindOwnerAsync(MembershipCashierUnified.Contracts.OwnerDiscriminator d);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILowLevelAccess/FindProfileCredit", ReplyAction="http://tempuri.org/ILowLevelAccess/FindProfileCreditResponse")]
        MembershipCashierUnified.Contracts.ProfileCreditContract[] FindProfileCredit(MembershipCashierUnified.Contracts.ProfileCreditDiscriminator d);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILowLevelAccess/FindProfileCredit", ReplyAction="http://tempuri.org/ILowLevelAccess/FindProfileCreditResponse")]
        System.Threading.Tasks.Task<MembershipCashierUnified.Contracts.ProfileCreditContract[]> FindProfileCreditAsync(MembershipCashierUnified.Contracts.ProfileCreditDiscriminator d);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILowLevelAccess/UpdateProfileCredit", ReplyAction="http://tempuri.org/ILowLevelAccess/UpdateProfileCreditResponse")]
        void UpdateProfileCredit(MembershipCashierUnified.Contracts.ProfileCreditContract[] d, bool allowDefaultValues);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILowLevelAccess/UpdateProfileCredit", ReplyAction="http://tempuri.org/ILowLevelAccess/UpdateProfileCreditResponse")]
        System.Threading.Tasks.Task UpdateProfileCreditAsync(MembershipCashierUnified.Contracts.ProfileCreditContract[] d, bool allowDefaultValues);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LowLevelForMembershipCashierDLChannel : MembershipCashierDL.Tests.MPSvc.LowLevelForMembershipCashierDL, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LowLevelForMembershipCashierDLClient : System.ServiceModel.ClientBase<MembershipCashierDL.Tests.MPSvc.LowLevelForMembershipCashierDL>, MembershipCashierDL.Tests.MPSvc.LowLevelForMembershipCashierDL {
        
        public LowLevelForMembershipCashierDLClient() {
        }
        
        public LowLevelForMembershipCashierDLClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LowLevelForMembershipCashierDLClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LowLevelForMembershipCashierDLClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LowLevelForMembershipCashierDLClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MembershipCashierUnified.Contracts.CreditTransactionContract[] FindCreditTransaction(MembershipCashierUnified.Contracts.CreditTransactionDiscriminator d) {
            return base.Channel.FindCreditTransaction(d);
        }
        
        public System.Threading.Tasks.Task<MembershipCashierUnified.Contracts.CreditTransactionContract[]> FindCreditTransactionAsync(MembershipCashierUnified.Contracts.CreditTransactionDiscriminator d) {
            return base.Channel.FindCreditTransactionAsync(d);
        }
        
        public MembershipCashierUnified.Contracts.LocationContract[] FindLocation(MembershipCashierUnified.Contracts.LocationDiscriminator d) {
            return base.Channel.FindLocation(d);
        }
        
        public System.Threading.Tasks.Task<MembershipCashierUnified.Contracts.LocationContract[]> FindLocationAsync(MembershipCashierUnified.Contracts.LocationDiscriminator d) {
            return base.Channel.FindLocationAsync(d);
        }
        
        public MembershipCashierUnified.Contracts.OwnerContract[] FindOwner(MembershipCashierUnified.Contracts.OwnerDiscriminator d) {
            return base.Channel.FindOwner(d);
        }
        
        public System.Threading.Tasks.Task<MembershipCashierUnified.Contracts.OwnerContract[]> FindOwnerAsync(MembershipCashierUnified.Contracts.OwnerDiscriminator d) {
            return base.Channel.FindOwnerAsync(d);
        }
        
        public MembershipCashierUnified.Contracts.ProfileCreditContract[] FindProfileCredit(MembershipCashierUnified.Contracts.ProfileCreditDiscriminator d) {
            return base.Channel.FindProfileCredit(d);
        }
        
        public System.Threading.Tasks.Task<MembershipCashierUnified.Contracts.ProfileCreditContract[]> FindProfileCreditAsync(MembershipCashierUnified.Contracts.ProfileCreditDiscriminator d) {
            return base.Channel.FindProfileCreditAsync(d);
        }
        
        public void UpdateProfileCredit(MembershipCashierUnified.Contracts.ProfileCreditContract[] d, bool allowDefaultValues) {
            base.Channel.UpdateProfileCredit(d, allowDefaultValues);
        }
        
        public System.Threading.Tasks.Task UpdateProfileCreditAsync(MembershipCashierUnified.Contracts.ProfileCreditContract[] d, bool allowDefaultValues) {
            return base.Channel.UpdateProfileCreditAsync(d, allowDefaultValues);
        }
    }
}
