//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MembershipCashierDL.Tests.SecuritySvc {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Node", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.MemberBindingNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.MemberNodeGeneric))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.TypeNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.MethodInfoNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.PropertyInfoNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.ConstructorInfoNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.FieldInfoNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.MemberInfoNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.MemberMemberBindingNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.MemberListBindingNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.ElementInitNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.MemberAssignmentNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.ExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.ExpressionNodeGeneric))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.MemberInitExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.NewExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.ConditionalExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.MethodCallExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.NewArrayExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.MemberExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.ParameterExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.TypeBinaryExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.UnaryExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.BinaryExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.ConstantExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.InvocationExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.LambdaExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.ListInitExpressionNode))]
    public partial class Node : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MemberBindingNode", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.MemberMemberBindingNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.MemberListBindingNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.MemberAssignmentNode))]
    public partial class MemberBindingNode : MembershipCashierDL.Tests.SecuritySvc.Node {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Linq.Expressions.MemberBindingType BindingTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.SecuritySvc.MemberInfoNode MemberField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Linq.Expressions.MemberBindingType BindingType {
            get {
                return this.BindingTypeField;
            }
            set {
                if ((this.BindingTypeField.Equals(value) != true)) {
                    this.BindingTypeField = value;
                    this.RaisePropertyChanged("BindingType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.SecuritySvc.MemberInfoNode Member {
            get {
                return this.MemberField;
            }
            set {
                if ((object.ReferenceEquals(this.MemberField, value) != true)) {
                    this.MemberField = value;
                    this.RaisePropertyChanged("Member");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MemberNodeGeneric", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.MethodInfoNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.PropertyInfoNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.ConstructorInfoNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.FieldInfoNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.MemberInfoNode))]
    public partial class MemberNodeGeneric : MembershipCashierDL.Tests.SecuritySvc.Node {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.SecuritySvc.TypeNode DeclaringTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SignatureField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.SecuritySvc.TypeNode DeclaringType {
            get {
                return this.DeclaringTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.DeclaringTypeField, value) != true)) {
                    this.DeclaringTypeField = value;
                    this.RaisePropertyChanged("DeclaringType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Signature {
            get {
                return this.SignatureField;
            }
            set {
                if ((object.ReferenceEquals(this.SignatureField, value) != true)) {
                    this.SignatureField = value;
                    this.RaisePropertyChanged("Signature");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TypeNode", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes")]
    [System.SerializableAttribute()]
    public partial class TypeNode : MembershipCashierDL.Tests.SecuritySvc.Node {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.SecuritySvc.TypeNode[] GenericArgumentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.SecuritySvc.TypeNode[] GenericArguments {
            get {
                return this.GenericArgumentsField;
            }
            set {
                if ((object.ReferenceEquals(this.GenericArgumentsField, value) != true)) {
                    this.GenericArgumentsField = value;
                    this.RaisePropertyChanged("GenericArguments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MethodInfoNode", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes")]
    [System.SerializableAttribute()]
    public partial class MethodInfoNode : MembershipCashierDL.Tests.SecuritySvc.MemberNodeGeneric {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.SecuritySvc.TypeNode[] GenericArgumentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsGenericMethodField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.SecuritySvc.TypeNode[] GenericArguments {
            get {
                return this.GenericArgumentsField;
            }
            set {
                if ((object.ReferenceEquals(this.GenericArgumentsField, value) != true)) {
                    this.GenericArgumentsField = value;
                    this.RaisePropertyChanged("GenericArguments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public bool IsGenericMethod {
            get {
                return this.IsGenericMethodField;
            }
            set {
                if ((this.IsGenericMethodField.Equals(value) != true)) {
                    this.IsGenericMethodField = value;
                    this.RaisePropertyChanged("IsGenericMethod");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PropertyInfoNode", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes")]
    [System.SerializableAttribute()]
    public partial class PropertyInfoNode : MembershipCashierDL.Tests.SecuritySvc.MemberNodeGeneric {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConstructorInfoNode", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes")]
    [System.SerializableAttribute()]
    public partial class ConstructorInfoNode : MembershipCashierDL.Tests.SecuritySvc.MemberNodeGeneric {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FieldInfoNode", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes")]
    [System.SerializableAttribute()]
    public partial class FieldInfoNode : MembershipCashierDL.Tests.SecuritySvc.MemberNodeGeneric {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MemberInfoNode", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes")]
    [System.SerializableAttribute()]
    public partial class MemberInfoNode : MembershipCashierDL.Tests.SecuritySvc.MemberNodeGeneric {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MemberMemberBindingNode", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes")]
    [System.SerializableAttribute()]
    public partial class MemberMemberBindingNode : MembershipCashierDL.Tests.SecuritySvc.MemberBindingNode {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.SecuritySvc.MemberBindingNodeList BindingsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.SecuritySvc.MemberBindingNodeList Bindings {
            get {
                return this.BindingsField;
            }
            set {
                if ((object.ReferenceEquals(this.BindingsField, value) != true)) {
                    this.BindingsField = value;
                    this.RaisePropertyChanged("Bindings");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MemberListBindingNode", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes")]
    [System.SerializableAttribute()]
    public partial class MemberListBindingNode : MembershipCashierDL.Tests.SecuritySvc.MemberBindingNode {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.SecuritySvc.ElementInitNodeList InitializersField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.SecuritySvc.ElementInitNodeList Initializers {
            get {
                return this.InitializersField;
            }
            set {
                if ((object.ReferenceEquals(this.InitializersField, value) != true)) {
                    this.InitializersField = value;
                    this.RaisePropertyChanged("Initializers");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ElementInitNode", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes")]
    [System.SerializableAttribute()]
    public partial class ElementInitNode : MembershipCashierDL.Tests.SecuritySvc.Node {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.SecuritySvc.MethodInfoNode AddMethodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.SecuritySvc.ExpressionNodeList ArgumentsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.SecuritySvc.MethodInfoNode AddMethod {
            get {
                return this.AddMethodField;
            }
            set {
                if ((object.ReferenceEquals(this.AddMethodField, value) != true)) {
                    this.AddMethodField = value;
                    this.RaisePropertyChanged("AddMethod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.SecuritySvc.ExpressionNodeList Arguments {
            get {
                return this.ArgumentsField;
            }
            set {
                if ((object.ReferenceEquals(this.ArgumentsField, value) != true)) {
                    this.ArgumentsField = value;
                    this.RaisePropertyChanged("Arguments");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MemberAssignmentNode", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes")]
    [System.SerializableAttribute()]
    public partial class MemberAssignmentNode : MembershipCashierDL.Tests.SecuritySvc.MemberBindingNode {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.SecuritySvc.ExpressionNode ExpressionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.SecuritySvc.ExpressionNode Expression {
            get {
                return this.ExpressionField;
            }
            set {
                if ((object.ReferenceEquals(this.ExpressionField, value) != true)) {
                    this.ExpressionField = value;
                    this.RaisePropertyChanged("Expression");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExpressionNode", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.ExpressionNodeGeneric))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.MemberInitExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.NewExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.ConditionalExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.MethodCallExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.NewArrayExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.MemberExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.ParameterExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.TypeBinaryExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.UnaryExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.BinaryExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.ConstantExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.InvocationExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.LambdaExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.ListInitExpressionNode))]
    public partial class ExpressionNode : MembershipCashierDL.Tests.SecuritySvc.Node {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Linq.Expressions.ExpressionType NodeTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.SecuritySvc.TypeNode TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Linq.Expressions.ExpressionType NodeType {
            get {
                return this.NodeTypeField;
            }
            set {
                if ((this.NodeTypeField.Equals(value) != true)) {
                    this.NodeTypeField = value;
                    this.RaisePropertyChanged("NodeType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.SecuritySvc.TypeNode Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExpressionNodeGeneric", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.MemberInitExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.NewExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.ConditionalExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.MethodCallExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.NewArrayExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.MemberExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.ParameterExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.TypeBinaryExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.UnaryExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.BinaryExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.ConstantExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.InvocationExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.LambdaExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.ListInitExpressionNode))]
    public partial class ExpressionNodeGeneric : MembershipCashierDL.Tests.SecuritySvc.ExpressionNode {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MemberInitExpressionNode", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes")]
    [System.SerializableAttribute()]
    public partial class MemberInitExpressionNode : MembershipCashierDL.Tests.SecuritySvc.ExpressionNodeGeneric {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.SecuritySvc.MemberBindingNodeList BindingsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.SecuritySvc.NewExpressionNode NewExpressionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.SecuritySvc.MemberBindingNodeList Bindings {
            get {
                return this.BindingsField;
            }
            set {
                if ((object.ReferenceEquals(this.BindingsField, value) != true)) {
                    this.BindingsField = value;
                    this.RaisePropertyChanged("Bindings");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.SecuritySvc.NewExpressionNode NewExpression {
            get {
                return this.NewExpressionField;
            }
            set {
                if ((object.ReferenceEquals(this.NewExpressionField, value) != true)) {
                    this.NewExpressionField = value;
                    this.RaisePropertyChanged("NewExpression");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NewExpressionNode", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes")]
    [System.SerializableAttribute()]
    public partial class NewExpressionNode : MembershipCashierDL.Tests.SecuritySvc.ExpressionNodeGeneric {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.SecuritySvc.ExpressionNodeList ArgumentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.SecuritySvc.ConstructorInfoNode ConstructorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.SecuritySvc.MemberInfoNodeList MembersField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.SecuritySvc.ExpressionNodeList Arguments {
            get {
                return this.ArgumentsField;
            }
            set {
                if ((object.ReferenceEquals(this.ArgumentsField, value) != true)) {
                    this.ArgumentsField = value;
                    this.RaisePropertyChanged("Arguments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.SecuritySvc.ConstructorInfoNode Constructor {
            get {
                return this.ConstructorField;
            }
            set {
                if ((object.ReferenceEquals(this.ConstructorField, value) != true)) {
                    this.ConstructorField = value;
                    this.RaisePropertyChanged("Constructor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.SecuritySvc.MemberInfoNodeList Members {
            get {
                return this.MembersField;
            }
            set {
                if ((object.ReferenceEquals(this.MembersField, value) != true)) {
                    this.MembersField = value;
                    this.RaisePropertyChanged("Members");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConditionalExpressionNode", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes")]
    [System.SerializableAttribute()]
    public partial class ConditionalExpressionNode : MembershipCashierDL.Tests.SecuritySvc.ExpressionNodeGeneric {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.SecuritySvc.ExpressionNode IfFalseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.SecuritySvc.ExpressionNode IfTrueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.SecuritySvc.ExpressionNode TestField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.SecuritySvc.ExpressionNode IfFalse {
            get {
                return this.IfFalseField;
            }
            set {
                if ((object.ReferenceEquals(this.IfFalseField, value) != true)) {
                    this.IfFalseField = value;
                    this.RaisePropertyChanged("IfFalse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.SecuritySvc.ExpressionNode IfTrue {
            get {
                return this.IfTrueField;
            }
            set {
                if ((object.ReferenceEquals(this.IfTrueField, value) != true)) {
                    this.IfTrueField = value;
                    this.RaisePropertyChanged("IfTrue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.SecuritySvc.ExpressionNode Test {
            get {
                return this.TestField;
            }
            set {
                if ((object.ReferenceEquals(this.TestField, value) != true)) {
                    this.TestField = value;
                    this.RaisePropertyChanged("Test");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MethodCallExpressionNode", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes")]
    [System.SerializableAttribute()]
    public partial class MethodCallExpressionNode : MembershipCashierDL.Tests.SecuritySvc.ExpressionNodeGeneric {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.SecuritySvc.ExpressionNodeList ArgumentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.SecuritySvc.MethodInfoNode MethodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.SecuritySvc.ExpressionNode ObjectField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.SecuritySvc.ExpressionNodeList Arguments {
            get {
                return this.ArgumentsField;
            }
            set {
                if ((object.ReferenceEquals(this.ArgumentsField, value) != true)) {
                    this.ArgumentsField = value;
                    this.RaisePropertyChanged("Arguments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.SecuritySvc.MethodInfoNode Method {
            get {
                return this.MethodField;
            }
            set {
                if ((object.ReferenceEquals(this.MethodField, value) != true)) {
                    this.MethodField = value;
                    this.RaisePropertyChanged("Method");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.SecuritySvc.ExpressionNode Object {
            get {
                return this.ObjectField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjectField, value) != true)) {
                    this.ObjectField = value;
                    this.RaisePropertyChanged("Object");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NewArrayExpressionNode", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes")]
    [System.SerializableAttribute()]
    public partial class NewArrayExpressionNode : MembershipCashierDL.Tests.SecuritySvc.ExpressionNodeGeneric {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.SecuritySvc.ExpressionNodeList ExpressionsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.SecuritySvc.ExpressionNodeList Expressions {
            get {
                return this.ExpressionsField;
            }
            set {
                if ((object.ReferenceEquals(this.ExpressionsField, value) != true)) {
                    this.ExpressionsField = value;
                    this.RaisePropertyChanged("Expressions");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MemberExpressionNode", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes")]
    [System.SerializableAttribute()]
    public partial class MemberExpressionNode : MembershipCashierDL.Tests.SecuritySvc.ExpressionNodeGeneric {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.SecuritySvc.ExpressionNode ExpressionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.SecuritySvc.MemberInfoNode MemberField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.SecuritySvc.ExpressionNode Expression {
            get {
                return this.ExpressionField;
            }
            set {
                if ((object.ReferenceEquals(this.ExpressionField, value) != true)) {
                    this.ExpressionField = value;
                    this.RaisePropertyChanged("Expression");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.SecuritySvc.MemberInfoNode Member {
            get {
                return this.MemberField;
            }
            set {
                if ((object.ReferenceEquals(this.MemberField, value) != true)) {
                    this.MemberField = value;
                    this.RaisePropertyChanged("Member");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParameterExpressionNode", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes")]
    [System.SerializableAttribute()]
    public partial class ParameterExpressionNode : MembershipCashierDL.Tests.SecuritySvc.ExpressionNodeGeneric {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsByRefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public bool IsByRef {
            get {
                return this.IsByRefField;
            }
            set {
                if ((this.IsByRefField.Equals(value) != true)) {
                    this.IsByRefField = value;
                    this.RaisePropertyChanged("IsByRef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TypeBinaryExpressionNode", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes")]
    [System.SerializableAttribute()]
    public partial class TypeBinaryExpressionNode : MembershipCashierDL.Tests.SecuritySvc.ExpressionNodeGeneric {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.SecuritySvc.ExpressionNode ExpressionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.SecuritySvc.TypeNode TypeOperandField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.SecuritySvc.ExpressionNode Expression {
            get {
                return this.ExpressionField;
            }
            set {
                if ((object.ReferenceEquals(this.ExpressionField, value) != true)) {
                    this.ExpressionField = value;
                    this.RaisePropertyChanged("Expression");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.SecuritySvc.TypeNode TypeOperand {
            get {
                return this.TypeOperandField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeOperandField, value) != true)) {
                    this.TypeOperandField = value;
                    this.RaisePropertyChanged("TypeOperand");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnaryExpressionNode", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes")]
    [System.SerializableAttribute()]
    public partial class UnaryExpressionNode : MembershipCashierDL.Tests.SecuritySvc.ExpressionNodeGeneric {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.SecuritySvc.ExpressionNode OperandField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.SecuritySvc.ExpressionNode Operand {
            get {
                return this.OperandField;
            }
            set {
                if ((object.ReferenceEquals(this.OperandField, value) != true)) {
                    this.OperandField = value;
                    this.RaisePropertyChanged("Operand");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BinaryExpressionNode", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes")]
    [System.SerializableAttribute()]
    public partial class BinaryExpressionNode : MembershipCashierDL.Tests.SecuritySvc.ExpressionNodeGeneric {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.SecuritySvc.ExpressionNode ConversionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsLiftedToNullField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.SecuritySvc.ExpressionNode LeftField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.SecuritySvc.MethodInfoNode MethodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.SecuritySvc.ExpressionNode RightField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.SecuritySvc.ExpressionNode Conversion {
            get {
                return this.ConversionField;
            }
            set {
                if ((object.ReferenceEquals(this.ConversionField, value) != true)) {
                    this.ConversionField = value;
                    this.RaisePropertyChanged("Conversion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public bool IsLiftedToNull {
            get {
                return this.IsLiftedToNullField;
            }
            set {
                if ((this.IsLiftedToNullField.Equals(value) != true)) {
                    this.IsLiftedToNullField = value;
                    this.RaisePropertyChanged("IsLiftedToNull");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.SecuritySvc.ExpressionNode Left {
            get {
                return this.LeftField;
            }
            set {
                if ((object.ReferenceEquals(this.LeftField, value) != true)) {
                    this.LeftField = value;
                    this.RaisePropertyChanged("Left");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.SecuritySvc.MethodInfoNode Method {
            get {
                return this.MethodField;
            }
            set {
                if ((object.ReferenceEquals(this.MethodField, value) != true)) {
                    this.MethodField = value;
                    this.RaisePropertyChanged("Method");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.SecuritySvc.ExpressionNode Right {
            get {
                return this.RightField;
            }
            set {
                if ((object.ReferenceEquals(this.RightField, value) != true)) {
                    this.RightField = value;
                    this.RaisePropertyChanged("Right");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConstantExpressionNode", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SecurityUnified.Contracts.RoleContract[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SecurityUnified.Contracts.RoleContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SecurityUnified.Contracts.RoleDiscriminator))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SecurityUnified.Contracts.DataDiscriminator<object>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SecurityUnified.Contracts.UserProfileContract[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SecurityUnified.Contracts.UserProfileContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SecurityUnified.Contracts.UserProfileImplementor))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SecurityUnified.Contracts.UserProfileDiscriminator))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SecurityUnified.Contracts.ExtendedUserProfileContract[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SecurityUnified.Contracts.ExtendedUserProfileContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SecurityUnified.Contracts.WebPagesMembershipImplementor))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Linq.Expressions.MemberBindingType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Linq.Expressions.ExpressionType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.ExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.Node))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.MemberMemberBindingNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.MemberBindingNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.MemberInfoNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.MemberNodeGeneric))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.TypeNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.TypeNode[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.MemberInfoNodeList))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.MemberInitExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.ExpressionNodeGeneric))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.MemberListBindingNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.ElementInitNodeList))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.ElementInitNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.MethodInfoNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.ConditionalExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.MethodCallExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.ExpressionNodeList))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.NewArrayExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.MemberExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.ParameterExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.PropertyInfoNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.TypeBinaryExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.UnaryExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.MemberBindingNodeList))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.BinaryExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.MemberAssignmentNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.NewExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.ConstructorInfoNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.FieldInfoNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.InvocationExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.LambdaExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.ListInitExpressionNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.ExpressionNode[]))]
    public partial class ConstantExpressionNode : MembershipCashierDL.Tests.SecuritySvc.ExpressionNodeGeneric {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public object Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvocationExpressionNode", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes")]
    [System.SerializableAttribute()]
    public partial class InvocationExpressionNode : MembershipCashierDL.Tests.SecuritySvc.ExpressionNodeGeneric {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.SecuritySvc.ExpressionNodeList ArgumentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.SecuritySvc.ExpressionNode ExpressionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.SecuritySvc.ExpressionNodeList Arguments {
            get {
                return this.ArgumentsField;
            }
            set {
                if ((object.ReferenceEquals(this.ArgumentsField, value) != true)) {
                    this.ArgumentsField = value;
                    this.RaisePropertyChanged("Arguments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.SecuritySvc.ExpressionNode Expression {
            get {
                return this.ExpressionField;
            }
            set {
                if ((object.ReferenceEquals(this.ExpressionField, value) != true)) {
                    this.ExpressionField = value;
                    this.RaisePropertyChanged("Expression");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LambdaExpressionNode", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes")]
    [System.SerializableAttribute()]
    public partial class LambdaExpressionNode : MembershipCashierDL.Tests.SecuritySvc.ExpressionNodeGeneric {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.SecuritySvc.ExpressionNode BodyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.SecuritySvc.ExpressionNodeList ParametersField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.SecuritySvc.ExpressionNode Body {
            get {
                return this.BodyField;
            }
            set {
                if ((object.ReferenceEquals(this.BodyField, value) != true)) {
                    this.BodyField = value;
                    this.RaisePropertyChanged("Body");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.SecuritySvc.ExpressionNodeList Parameters {
            get {
                return this.ParametersField;
            }
            set {
                if ((object.ReferenceEquals(this.ParametersField, value) != true)) {
                    this.ParametersField = value;
                    this.RaisePropertyChanged("Parameters");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListInitExpressionNode", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes")]
    [System.SerializableAttribute()]
    public partial class ListInitExpressionNode : MembershipCashierDL.Tests.SecuritySvc.ExpressionNodeGeneric {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.SecuritySvc.ElementInitNodeList InitializersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MembershipCashierDL.Tests.SecuritySvc.ExpressionNode NewExpressionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.SecuritySvc.ElementInitNodeList Initializers {
            get {
                return this.InitializersField;
            }
            set {
                if ((object.ReferenceEquals(this.InitializersField, value) != true)) {
                    this.InitializersField = value;
                    this.RaisePropertyChanged("Initializers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MembershipCashierDL.Tests.SecuritySvc.ExpressionNode NewExpression {
            get {
                return this.NewExpressionField;
            }
            set {
                if ((object.ReferenceEquals(this.NewExpressionField, value) != true)) {
                    this.NewExpressionField = value;
                    this.RaisePropertyChanged("NewExpression");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="MemberBindingNodeList", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes", ItemName="MemberBindingNode")]
    [System.SerializableAttribute()]
    public class MemberBindingNodeList : System.Collections.Generic.List<MembershipCashierDL.Tests.SecuritySvc.MemberBindingNode> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ElementInitNodeList", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes", ItemName="ElementInitNode")]
    [System.SerializableAttribute()]
    public class ElementInitNodeList : System.Collections.Generic.List<MembershipCashierDL.Tests.SecuritySvc.ElementInitNode> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ExpressionNodeList", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes", ItemName="ExpressionNode")]
    [System.SerializableAttribute()]
    public class ExpressionNodeList : System.Collections.Generic.List<MembershipCashierDL.Tests.SecuritySvc.ExpressionNode> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="MemberInfoNodeList", Namespace="http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes", ItemName="MemberInfoNode")]
    [System.SerializableAttribute()]
    public class MemberInfoNodeList : System.Collections.Generic.List<MembershipCashierDL.Tests.SecuritySvc.MemberInfoNode> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SecuritySvc.LowLevelForSecurityDL")]
    public interface LowLevelForSecurityDL {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILowLevelAccess/GetUserRoles", ReplyAction="http://tempuri.org/ILowLevelAccess/GetUserRolesResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SecurityUnified.Contracts.RoleContract[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SecurityUnified.Contracts.RoleContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SecurityUnified.Contracts.RoleDiscriminator))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SecurityUnified.Contracts.DataDiscriminator<object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SecurityUnified.Contracts.UserProfileContract[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SecurityUnified.Contracts.UserProfileContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SecurityUnified.Contracts.UserProfileImplementor))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SecurityUnified.Contracts.UserProfileDiscriminator))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SecurityUnified.Contracts.ExtendedUserProfileContract[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SecurityUnified.Contracts.ExtendedUserProfileContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SecurityUnified.Contracts.WebPagesMembershipImplementor))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Linq.Expressions.MemberBindingType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Linq.Expressions.ExpressionType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.ExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.Node))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.MemberMemberBindingNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.MemberBindingNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.MemberInfoNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.MemberNodeGeneric))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.TypeNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.TypeNode[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.MemberInfoNodeList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.MemberInitExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.ExpressionNodeGeneric))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.MemberListBindingNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.ElementInitNodeList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.ElementInitNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.MethodInfoNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.ConditionalExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.MethodCallExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.ExpressionNodeList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.NewArrayExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.MemberExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.ParameterExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.PropertyInfoNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.TypeBinaryExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.UnaryExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.MemberBindingNodeList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.BinaryExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.MemberAssignmentNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.ConstantExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.NewExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.ConstructorInfoNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.FieldInfoNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.InvocationExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.LambdaExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.ListInitExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.ExpressionNode[]))]
        SecurityUnified.Contracts.RoleContract[] GetUserRoles(object user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILowLevelAccess/GetUserRoles", ReplyAction="http://tempuri.org/ILowLevelAccess/GetUserRolesResponse")]
        System.Threading.Tasks.Task<SecurityUnified.Contracts.RoleContract[]> GetUserRolesAsync(object user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILowLevelAccess/AddRoleToUser", ReplyAction="http://tempuri.org/ILowLevelAccess/AddRoleToUserResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SecurityUnified.Contracts.RoleContract[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SecurityUnified.Contracts.RoleContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SecurityUnified.Contracts.RoleDiscriminator))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SecurityUnified.Contracts.DataDiscriminator<object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SecurityUnified.Contracts.UserProfileContract[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SecurityUnified.Contracts.UserProfileContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SecurityUnified.Contracts.UserProfileImplementor))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SecurityUnified.Contracts.UserProfileDiscriminator))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SecurityUnified.Contracts.ExtendedUserProfileContract[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SecurityUnified.Contracts.ExtendedUserProfileContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SecurityUnified.Contracts.WebPagesMembershipImplementor))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Linq.Expressions.MemberBindingType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Linq.Expressions.ExpressionType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.ExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.Node))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.MemberMemberBindingNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.MemberBindingNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.MemberInfoNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.MemberNodeGeneric))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.TypeNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.TypeNode[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.MemberInfoNodeList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.MemberInitExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.ExpressionNodeGeneric))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.MemberListBindingNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.ElementInitNodeList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.ElementInitNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.MethodInfoNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.ConditionalExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.MethodCallExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.ExpressionNodeList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.NewArrayExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.MemberExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.ParameterExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.PropertyInfoNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.TypeBinaryExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.UnaryExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.MemberBindingNodeList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.BinaryExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.MemberAssignmentNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.ConstantExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.NewExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.ConstructorInfoNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.FieldInfoNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.InvocationExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.LambdaExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.ListInitExpressionNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MembershipCashierDL.Tests.SecuritySvc.ExpressionNode[]))]
        void AddRoleToUser(object user, SecurityUnified.Contracts.RoleContract[] roles, int modifiedByUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILowLevelAccess/AddRoleToUser", ReplyAction="http://tempuri.org/ILowLevelAccess/AddRoleToUserResponse")]
        System.Threading.Tasks.Task AddRoleToUserAsync(object user, SecurityUnified.Contracts.RoleContract[] roles, int modifiedByUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILowLevelAccess/GetUsersInRole", ReplyAction="http://tempuri.org/ILowLevelAccess/GetUsersInRoleResponse")]
        SecurityUnified.Contracts.UserProfileContract[] GetUsersInRole(SecurityUnified.Contracts.RoleDiscriminator d);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILowLevelAccess/GetUsersInRole", ReplyAction="http://tempuri.org/ILowLevelAccess/GetUsersInRoleResponse")]
        System.Threading.Tasks.Task<SecurityUnified.Contracts.UserProfileContract[]> GetUsersInRoleAsync(SecurityUnified.Contracts.RoleDiscriminator d);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILowLevelAccess/GetRolesForUser", ReplyAction="http://tempuri.org/ILowLevelAccess/GetRolesForUserResponse")]
        SecurityUnified.Contracts.RoleContract[] GetRolesForUser(SecurityUnified.Contracts.UserProfileDiscriminator d);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILowLevelAccess/GetRolesForUser", ReplyAction="http://tempuri.org/ILowLevelAccess/GetRolesForUserResponse")]
        System.Threading.Tasks.Task<SecurityUnified.Contracts.RoleContract[]> GetRolesForUserAsync(SecurityUnified.Contracts.UserProfileDiscriminator d);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILowLevelAccess/FindUserProfile", ReplyAction="http://tempuri.org/ILowLevelAccess/FindUserProfileResponse")]
        SecurityUnified.Contracts.UserProfileContract[] FindUserProfile(SecurityUnified.Contracts.UserProfileDiscriminator d);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILowLevelAccess/FindUserProfile", ReplyAction="http://tempuri.org/ILowLevelAccess/FindUserProfileResponse")]
        System.Threading.Tasks.Task<SecurityUnified.Contracts.UserProfileContract[]> FindUserProfileAsync(SecurityUnified.Contracts.UserProfileDiscriminator d);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILowLevelAccess/FindExtendedUserProfile", ReplyAction="http://tempuri.org/ILowLevelAccess/FindExtendedUserProfileResponse")]
        SecurityUnified.Contracts.ExtendedUserProfileContract[] FindExtendedUserProfile(SecurityUnified.Contracts.UserProfileDiscriminator d);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILowLevelAccess/FindExtendedUserProfile", ReplyAction="http://tempuri.org/ILowLevelAccess/FindExtendedUserProfileResponse")]
        System.Threading.Tasks.Task<SecurityUnified.Contracts.ExtendedUserProfileContract[]> FindExtendedUserProfileAsync(SecurityUnified.Contracts.UserProfileDiscriminator d);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILowLevelAccess/FindRole", ReplyAction="http://tempuri.org/ILowLevelAccess/FindRoleResponse")]
        SecurityUnified.Contracts.RoleContract[] FindRole(SecurityUnified.Contracts.RoleDiscriminator d);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILowLevelAccess/FindRole", ReplyAction="http://tempuri.org/ILowLevelAccess/FindRoleResponse")]
        System.Threading.Tasks.Task<SecurityUnified.Contracts.RoleContract[]> FindRoleAsync(SecurityUnified.Contracts.RoleDiscriminator d);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILowLevelAccess/UpdateUserProfile", ReplyAction="http://tempuri.org/ILowLevelAccess/UpdateUserProfileResponse")]
        void UpdateUserProfile(SecurityUnified.Contracts.UserProfileContract[] d, int modifiedByUserId, bool allowDefaultValues);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILowLevelAccess/UpdateUserProfile", ReplyAction="http://tempuri.org/ILowLevelAccess/UpdateUserProfileResponse")]
        System.Threading.Tasks.Task UpdateUserProfileAsync(SecurityUnified.Contracts.UserProfileContract[] d, int modifiedByUserId, bool allowDefaultValues);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILowLevelAccess/InsertUserProfile", ReplyAction="http://tempuri.org/ILowLevelAccess/InsertUserProfileResponse")]
        void InsertUserProfile(SecurityUnified.Contracts.ExtendedUserProfileContract[] d);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILowLevelAccess/InsertUserProfile", ReplyAction="http://tempuri.org/ILowLevelAccess/InsertUserProfileResponse")]
        System.Threading.Tasks.Task InsertUserProfileAsync(SecurityUnified.Contracts.ExtendedUserProfileContract[] d);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LowLevelForSecurityDLChannel : MembershipCashierDL.Tests.SecuritySvc.LowLevelForSecurityDL, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LowLevelForSecurityDLClient : System.ServiceModel.ClientBase<MembershipCashierDL.Tests.SecuritySvc.LowLevelForSecurityDL>, MembershipCashierDL.Tests.SecuritySvc.LowLevelForSecurityDL {
        
        public LowLevelForSecurityDLClient() {
        }
        
        public LowLevelForSecurityDLClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LowLevelForSecurityDLClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LowLevelForSecurityDLClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LowLevelForSecurityDLClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SecurityUnified.Contracts.RoleContract[] GetUserRoles(object user) {
            return base.Channel.GetUserRoles(user);
        }
        
        public System.Threading.Tasks.Task<SecurityUnified.Contracts.RoleContract[]> GetUserRolesAsync(object user) {
            return base.Channel.GetUserRolesAsync(user);
        }
        
        public void AddRoleToUser(object user, SecurityUnified.Contracts.RoleContract[] roles, int modifiedByUserId) {
            base.Channel.AddRoleToUser(user, roles, modifiedByUserId);
        }
        
        public System.Threading.Tasks.Task AddRoleToUserAsync(object user, SecurityUnified.Contracts.RoleContract[] roles, int modifiedByUserId) {
            return base.Channel.AddRoleToUserAsync(user, roles, modifiedByUserId);
        }
        
        public SecurityUnified.Contracts.UserProfileContract[] GetUsersInRole(SecurityUnified.Contracts.RoleDiscriminator d) {
            return base.Channel.GetUsersInRole(d);
        }
        
        public System.Threading.Tasks.Task<SecurityUnified.Contracts.UserProfileContract[]> GetUsersInRoleAsync(SecurityUnified.Contracts.RoleDiscriminator d) {
            return base.Channel.GetUsersInRoleAsync(d);
        }
        
        public SecurityUnified.Contracts.RoleContract[] GetRolesForUser(SecurityUnified.Contracts.UserProfileDiscriminator d) {
            return base.Channel.GetRolesForUser(d);
        }
        
        public System.Threading.Tasks.Task<SecurityUnified.Contracts.RoleContract[]> GetRolesForUserAsync(SecurityUnified.Contracts.UserProfileDiscriminator d) {
            return base.Channel.GetRolesForUserAsync(d);
        }
        
        public SecurityUnified.Contracts.UserProfileContract[] FindUserProfile(SecurityUnified.Contracts.UserProfileDiscriminator d) {
            return base.Channel.FindUserProfile(d);
        }
        
        public System.Threading.Tasks.Task<SecurityUnified.Contracts.UserProfileContract[]> FindUserProfileAsync(SecurityUnified.Contracts.UserProfileDiscriminator d) {
            return base.Channel.FindUserProfileAsync(d);
        }
        
        public SecurityUnified.Contracts.ExtendedUserProfileContract[] FindExtendedUserProfile(SecurityUnified.Contracts.UserProfileDiscriminator d) {
            return base.Channel.FindExtendedUserProfile(d);
        }
        
        public System.Threading.Tasks.Task<SecurityUnified.Contracts.ExtendedUserProfileContract[]> FindExtendedUserProfileAsync(SecurityUnified.Contracts.UserProfileDiscriminator d) {
            return base.Channel.FindExtendedUserProfileAsync(d);
        }
        
        public SecurityUnified.Contracts.RoleContract[] FindRole(SecurityUnified.Contracts.RoleDiscriminator d) {
            return base.Channel.FindRole(d);
        }
        
        public System.Threading.Tasks.Task<SecurityUnified.Contracts.RoleContract[]> FindRoleAsync(SecurityUnified.Contracts.RoleDiscriminator d) {
            return base.Channel.FindRoleAsync(d);
        }
        
        public void UpdateUserProfile(SecurityUnified.Contracts.UserProfileContract[] d, int modifiedByUserId, bool allowDefaultValues) {
            base.Channel.UpdateUserProfile(d, modifiedByUserId, allowDefaultValues);
        }
        
        public System.Threading.Tasks.Task UpdateUserProfileAsync(SecurityUnified.Contracts.UserProfileContract[] d, int modifiedByUserId, bool allowDefaultValues) {
            return base.Channel.UpdateUserProfileAsync(d, modifiedByUserId, allowDefaultValues);
        }
        
        public void InsertUserProfile(SecurityUnified.Contracts.ExtendedUserProfileContract[] d) {
            base.Channel.InsertUserProfile(d);
        }
        
        public System.Threading.Tasks.Task InsertUserProfileAsync(SecurityUnified.Contracts.ExtendedUserProfileContract[] d) {
            return base.Channel.InsertUserProfileAsync(d);
        }
    }
}
